<?php

// Get all tools names from `screenshots` directory
// and generate a JSON object with the tool name as key
// and an array of all screenshots as value.
//
// The array is generated by finding all JPG files in the tool directory
// and replacing the path with a URL to the raw file on GitHub.
//
// Encode all URLs with `rawurlencode()` to prevent issues with special characters.
//
// Example JSON output:
// {
//   "tool1": [
//     { 
//       "path": "/assets/branch/screenshots/tool1/screenshot1.jpg",
//       "url": "https://example.com"
//     },
//     { 
//       "path": "/assets/branch/screenshots/tool1/screenshot2.jpg",
//       "url": "https://example.com"
//     }
//   ],
//   "tool2": [
//     { 
//       "path": "/assets/branch/screenshots/tool2/screenshot1.jpg",
//       "url": "https://example.org/foo"
//     },
//   ]
// }
//
// Store the output in a file called `screenshots.json` in the root directory.


// Get all tools names from `screenshots` directory
$tools = array_diff(scandir('screenshots'), array('..', '.'));
$tools = array_values($tools);

// Generate JSON object
$json = array();
foreach ($tools as $tool) {
    $screenshots = array_diff(scandir('screenshots/' . $tool), array('..', '.'));
    $screenshots = array_values($screenshots);
    $json[$tool] = array();
    foreach ($screenshots as $screenshot) {
        // Get the last part of the path (the filename), remove the extension
        // and urldecode it to get the URL to the tool.
        $url = urldecode(pathinfo($screenshot, PATHINFO_FILENAME));

        // Urlencode screenshot to prevent issues with special characters
        $screenshot = rawurlencode($screenshot);

        // Full path to screenshot
        $path = $tool . '/' . $screenshot;

        // Prefix to get the URL to the raw file.
        $prefix = 'https://raw.githubusercontent.com/analysis-tools-dev/assets/master/screenshots/';

        $fullPath = $prefix . $path;

        // Add screenshot to JSON object
        $json[$tool][] = array(
            'path' => $fullPath,
            'url' => $url
        );
    }
}

file_put_contents('screenshots.json', json_encode($json, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));

