name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 4 * * 0"
  repository_dispatch:
    types: [rebuild]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run my action
        run: src/index.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: Commit new screenshots
          commit_user_name: Analysis Tools Bot
          commit_user_email: bot@analysis-tools.dev
          commit_author: Analysis Tools Bot <bot@analysis-tools.dev>
